language: node_js
node_js:
  - '12'
sudo: required

branches:
  only:
    - master

env:
  - DEPLOY_PATH="translator"

script:
  - sudo apt update
  - sudo apt install openjdk-8-jdk awscli -y
  - cd lambda
  - ./gradlew build shadowJar --no-daemon
  - cd ../infrastructure
  - npm i
  - npm run build
  - npm install -g aws-cdk
  - cdk synth
  - cdk deploy
  - cd ../frontend
  - npm i
  - ./updateApiUrl.sh
  - ./node_modules/@angular/cli/bin/ng build --prod --base-href /$DEPLOY_PATH/
  - ssh root@stnimmerlein.de "mkdir -p /var/www/html/$DEPLOY_PATH"
  - scp -r dist/frontend/* root@stnimmerlein.de:/var/www/html/$DEPLOY_PATH

notifications:
  email:
    recipients:
      - mail@stnimmerlein.de
    on_success: change
    on_failure: always

before_install:
  - echo -e "Host stnimmerlein.de\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - openssl aes-256-cbc -K $encrypted_d4824022e3f9_key -iv $encrypted_d4824022e3f9_iv -in deploy-key.enc -out deploy-key -d
  - eval "$(ssh-agent -s)"
  - chmod 400 ./deploy-key
  - ssh-add ./deploy-key
